version: "3.8"

services:
  n8n:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD} # Use an environment variable for security
      - N8N_HOST=localhost # Or your domain, e.g., n8n.example.com
      - N8N_PORT=5678
      - N8N_PROTOCOL=http # or https if using a reverse proxy with SSL
      - GENERIC_TIMEZONE=Europe/Berlin # Adjust to your timezone
      - TZ=Europe/Berlin # Adjust to your timezone
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=n8n
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} # Use an environment variable for security
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  n8n_data:
  postgres_data:
